services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recipe

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  recipe-service:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
        DB_URL: jdbc:postgresql://postgres:5432/recipe
        DB_USER: postgres
        DB_PASSWORD: password
        RABBIT_HOST: rabbitmq
        RABBIT_PORT: 5672
        RABBIT_USER: guest
        RABBIT_PASSWORD: guest
